spring.application.name=ledger-service

spring.datasource.url=jdbc:postgresql://localhost:5432/fincore
spring.datasource.username=fincore
spring.datasource.password=fincore

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

server.port=8081
